version: "3.7"

services:
  postgres:
    image: postgres:13.5
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql.conf:/etc/postgresql.conf
      - postgres_vol:/var/lib/postgresql/data
    networks:
      - net
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      TZ: ${TIMEZONE:-"Asia/Bangkok"}

volumes:
  postgres_vol:
    driver: local

networks:
  net:
    external: false
    driver: bridge
